---

- name: test for {'name': 'add_route'}
  uri:
    url: "{{tourist_test_url}}/act"
    method: POST
    body_format: json
    return_content: yes
    body: {
      "action": "add_route",
      "param": {}
    }
    register: {'name': 'add_route'}_result

- debug: var={'name': 'add_route'}_result.content


...